// DEPENDENCIES
import Head from 'next/head'

// COMPONENTS
import Sidebar from "../components/Sidebar";

// STYLES
const styles = {
    container: 'h-full w-full flex bg-white',
}

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Web3 Amazon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sidebar />

        </div>
    )
}
